# Generated by Django 2.0.3 on 2018-07-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Department ', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee ', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='salaries',
            options={'verbose_name': 'salary '},
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Department No'),
        ),
        migrations.AlterField(
            model_name='deptemp',
            name='dept_no',
            field=models.ForeignKey(db_column='dept_no', on_delete=django.db.models.deletion.CASCADE, to='ems.Departments'),
        ),
        migrations.AlterField(
            model_name='deptemp',
            name='emp_no',
            field=models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, to='ems.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Employee DOB'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=14, verbose_name='Employee First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Employee Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Employee Hire Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=16, verbose_name='Employee Last Name'),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='emp_no',
            field=models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, to='ems.Employee'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='emp_no',
            field=models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, to='ems.Employee'),
        ),
    ]
