# Generated by Django 2.0.3 on 2018-07-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(help_text='Enter Project ID', verbose_name='Project ID')),
                ('project_name', models.CharField(help_text='Project Name', max_length=200, verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'Project Names',
                'verbose_name_plural': 'Project Names',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='TimeMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(help_text='Enter The Menu ID', verbose_name='Menu ID')),
                ('menu_name', models.CharField(help_text='Menu Name', max_length=200, verbose_name='Menu Name')),
                ('menu_desc', models.CharField(help_text='Menu details', max_length=200, verbose_name=' Menu Description')),
                ('menu_url', models.CharField(help_text='Menu URL', max_length=200, verbose_name=' Menu URL')),
            ],
            options={
                'verbose_name': 'Time Menus',
                'verbose_name_plural': 'Time Menus',
                'ordering': ['menu_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='Employee ID')),
                ('ts_date', models.DateField(verbose_name='Time Sheet Date')),
                ('ts_effort', models.PositiveIntegerField(default=8, verbose_name='Hours worked')),
                ('ts_desc', models.CharField(max_length=200, verbose_name='Time Description')),
            ],
            options={
                'verbose_name': 'Time Records',
                'verbose_name_plural': 'Time Records',
                'ordering': ['-emp_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='timerecords',
            unique_together={('emp_id', 'ts_date')},
        ),
    ]
