# Generated by Django 2.0.6 on 2018-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=5)),
                ('ts_date', models.DateField()),
                ('ts_effort', models.IntegerField(max_length=2)),
                ('ts_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
