# Generated by Django 2.0.3 on 2018-09-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboxBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_body', models.CharField(max_length=2000, verbose_name='Message Body')),
            ],
        ),
        migrations.CreateModel(
            name='InboxHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.PositiveIntegerField(verbose_name='Message ID')),
                ('from_id', models.PositiveIntegerField(verbose_name='From ID')),
                ('sent_date', models.DateField(verbose_name='sent Date')),
                ('parent_msg_id', models.PositiveIntegerField(verbose_name='Message ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Message Subject')),
            ],
            options={
                'verbose_name': 'Inbox Header',
                'verbose_name_plural': 'Inbox Header',
                'ordering': ['msg_id'],
            },
        ),
        migrations.CreateModel(
            name='InboxRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.PositiveIntegerField(verbose_name='To ID')),
                ('status', models.CharField(choices=[('R', 'READ'), ('U', 'UNREAD'), ('D', 'DELETED'), ('A', 'ARCHIVED')], default='U', max_length=1, verbose_name='Read Status')),
                ('read_date', models.DateField(verbose_name='read Date')),
                ('msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.InboxHeader')),
            ],
            options={
                'verbose_name': 'Inbox Recipient',
                'verbose_name_plural': 'Inbox Recipient',
                'ordering': ['msg_id'],
            },
        ),
        migrations.AddField(
            model_name='inboxbody',
            name='msg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.InboxHeader'),
        ),
    ]
