# Generated by Django 2.0.3 on 2018-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lms_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField(help_text='Enter The Employee ID', verbose_name='Employee ID')),
                ('ls_total', models.PositiveIntegerField(help_text='Total Leaves', verbose_name='Total Leaves')),
                ('ls_availed', models.PositiveIntegerField(help_text='Availed Leaves', verbose_name='Availed Leaves')),
                ('ls_balance', models.PositiveIntegerField(help_text='Balance Leaves', verbose_name='Balance Leaves')),
            ],
            options={
                'verbose_name': 'Leave Count',
                'verbose_name_plural': 'Leave Count',
                'ordering': ['emp_id'],
            },
        ),
        migrations.CreateModel(
            name='lms_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField(help_text='Enter The Employee ID', verbose_name='Employee ID')),
                ('ls_date', models.DateField(verbose_name='Leave Date')),
                ('ls_reason', models.CharField(help_text='Reason for taking Leave', max_length=200, verbose_name='Reason for taking Leave')),
                ('ls_status', models.CharField(choices=[('A', 'APPROVED'), ('P', 'PENDING'), ('R', 'REJECTED')], default='P', max_length=1, verbose_name='Leave Status')),
            ],
            options={
                'verbose_name': 'Leave Details',
                'verbose_name_plural': 'Leave Details',
                'ordering': ['ls_date'],
            },
        ),
    ]
